### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by spencerthayer** [mbrashid62/encrypto-chat#1]
Or was it abandoned? How does it or was it supposed to work?

**Comment by yujhuang** [comment]
Right now，it is more likely to work on Chrome.

**Comment by yujhuang** [comment]
There are potential problems. Since this was originally for demo purpose, so it works only for two connections. 
If you wanna see it working，start the server by command line command “node app.js” and start two instances on chrome.

**Comment by spencerthayer** [comment]
Not working.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle encrypto-chat@0.0.0~prestart: encrypto-chat@0.0.0
6 silly lifecycle encrypto-chat@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle encrypto-chat@0.0.0~start: encrypto-chat@0.0.0
8 verbose lifecycle encrypto-chat@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle encrypto-chat@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/PATH/Encrypto-Chat-master/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
10 verbose lifecycle encrypto-chat@0.0.0~start: CWD: /PATH/Encrypto-Chat-master
11 silly lifecycle encrypto-chat@0.0.0~start: Args: [ '-c', 'grunt run' ]
12 silly lifecycle encrypto-chat@0.0.0~start: Returned: code: 99  signal: null
13 info lifecycle encrypto-chat@0.0.0~start: Failed to exec start script
14 verbose stack Error: encrypto-chat@0.0.0 start: `grunt run`
14 verbose stack Exit status 99
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid encrypto-chat@0.0.0
16 verbose cwd /Users/spencerthayer/Downloads/Encrypto-Chat-master
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error encrypto-chat@0.0.0 start: `grunt run`
22 error Exit status 99
23 error Failed at the encrypto-chat@0.0.0 start script 'grunt run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the encrypto-chat package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs encrypto-chat
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls encrypto-chat
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by spencerthayer** [comment]
Anyway, I ask because I would like to integrate SMP into my E2EE javascript chat solution [TorchNoteJS](https://github.com/spencerthayer/TorchNoteJS).

**Comment by yujhuang** [comment]
okay, are you having problem start the node.js server?

**Comment by yujhuang** [comment]
I just tested it using webstorm, it works perfectly fine.
I would say go to another repo: https://github.com/yujhuang/Myencrypto-chat
The main difference is only styling and some minor configuration, but that one has a demo.
Please close this issue, because it really worked.
![image](https://cloud.githubusercontent.com/assets/13956452/20824928/17ebdb78-b826-11e6-9d8a-ea9b6deeeaac.png)
![image](https://cloud.githubusercontent.com/assets/13956452/20824943/29dbed50-b826-11e6-92e1-1174d0984e66.png)

**Comment by spencerthayer** [comment]
Cool.
